const NOTIFICATION_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  RETRYING: 'RETRYING',
  DELIVERED: 'DELIVERED',
  BOUNCED: 'BOUNCED',
  COMPLAINED: 'COMPLAINED',
  SCHEDULED: 'SCHEDULED',
  SUPPRESSED: 'SUPPRESSED',
};

const ATTEMPT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};

module.exports = {
  NOTIFICATION_STATUS,
  ATTEMPT_STATUS,
};
