const PERMISSIONS = Object.freeze({
  ORGANIZATION_READ: 'ORGANIZATION_READ',
  ORGANIZATION_UPDATE: 'ORGANIZATION_UPDATE',
  ORGANIZATION_DELETE: 'ORGANIZATION_DELETE',

  MEMBERS_READ: 'MEMBERS_READ',
  MEMBERS_MANAGE: 'MEMBERS_MANAGE',
  MEMBERS_REMOVE: 'MEMBERS_REMOVE',

  PROJECTS_READ: 'PROJECTS_READ',
  PROJECTS_CREATE: 'PROJECTS_CREATE',
  PROJECTS_UPDATE: 'PROJECTS_UPDATE',
  PROJECTS_DELETE: 'PROJECTS_DELETE',

  API_KEYS_READ: 'API_KEYS_READ',
  API_KEYS_CREATE: 'API_KEYS_CREATE',
  API_KEYS_REVOKE: 'API_KEYS_REVOKE',
  API_KEYS_UPDATE: 'API_KEYS_UPDATE',

  TEMPLATES_READ: 'TEMPLATES_READ',
  TEMPLATES_CREATE: 'TEMPLATES_CREATE',
  TEMPLATES_UPDATE: 'TEMPLATES_UPDATE',
  TEMPLATES_DELETE: 'TEMPLATES_DELETE',

  NOTIFICATIONS_SEND: 'NOTIFICATIONS_SEND',
  NOTIFICATIONS_READ: 'NOTIFICATIONS_READ',
  NOTIFICATIONS_CANCEL: 'NOTIFICATIONS_CANCEL',

  ANALYTICS_READ: 'ANALYTICS_READ',

  WEBHOOKS_READ: 'WEBHOOKS_READ',
  WEBHOOKS_MANAGE: 'WEBHOOKS_MANAGE',
});

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ROLE_PERMISSIONS = Object.freeze({
  OWNER: ALL_PERMISSIONS,

  ADMIN: ALL_PERMISSIONS.filter(
    (p) => p !== PERMISSIONS.ORGANIZATION_DELETE
  ),

  MEMBER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.API_KEYS_READ,
    PERMISSIONS.TEMPLATES_READ,
    PERMISSIONS.TEMPLATES_CREATE,
    PERMISSIONS.TEMPLATES_UPDATE,
    PERMISSIONS.NOTIFICATIONS_SEND,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_CANCEL,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.WEBHOOKS_READ,
  ],

  VIEWER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.API_KEYS_READ,
    PERMISSIONS.TEMPLATES_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.WEBHOOKS_READ,
  ],
});

/**
 * Checks if a given role possesses a specific permission.
 *
 * @param {string} role
 * @param {string} permission
 * @returns {boolean}
 */
function hasPermission(role, permission) {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
