const SUPPRESSION_REASONS = Object.freeze({
  USER_PREFERENCE: 'USER_PREFERENCE',
  NO_ACTIVE_DEVICE: 'NO_ACTIVE_DEVICE',
  NO_VALID_RECIPIENT: 'NO_VALID_RECIPIENT',
  SYSTEM_POLICY: 'SYSTEM_POLICY',
  UNSUBSCRIBED: 'UNSUBSCRIBED',
});

module.exports = {
  SUPPRESSION_REASONS,
};
